{% set version = "2.12.0" %}

package:
  name: keras
  version: {{ version }}

source:
  - url: https://pypi.io/packages/py2.py3/k/keras/keras-{{ version }}-py2.py3-none-any.whl
    sha256: 35c39534011e909645fb93515452e98e1a0ce23727b55d4918b9c58b2308c15e

build:
  number: 3

requirements:
  host:
    - python {{ python }}
    - pip
  run:
    - python {{ python }}
    - keras-preprocessing >={{ keras_preprocessing }}
  run_constrained:
    - tensorflow {{ tensorflow }}

test:
  requires:
    - pip
  commands:
    - pip check
  # Cyclic dependency with tensorflow
  # imports:
  #  - keras

about:
  home: https://github.com/keras-team/keras
  license: MIT
  license_file: ../../LICENSE
  summary: Deep Learning for Python

extra:
  recipe-maintainers:
    - open-ce/open-ce-dev-team
