{% set version = "2.12.0" %}

package:
  name: keras
  version: {{ version }}

source:
  - url: https://pypi.io/packages/py2.py3/k/keras/keras-{{ version }}-py2.py3-none-any.whl
    sha256: 35c39534011e909645fb93515452e98e1a0ce23727b55d4918b9c58b2308c15e

build:
  noarch: python
  number: 3

requirements:
  build:
    - {{ compiler('c') }}      # [ ppc_arch != "p10"]
    - {{ compiler('cxx') }}    # [ ppc_arch != "p10"]
  host:
    - bazel {{ bazel }}
    - python           #[py>36]
    - pip
  run:
    - python           #[py>36]
    - pandas
    # Disabling pydot temporarily as it is not available for py39.
    # Even the one available for py38/py37 has conflict due to graphviz and pillow.
    #- pydot
    - portpicker
    - scipy {{ scipy }}
    - pyyaml {{ pyyaml }}
    - pillow
    - black {{ black }}

  run_constrained:
    - tensorflow {{ tensorflow }}.*

test:
  requires:
    - pip
  commands:
    - pip check
# Disabling these imports test  due to cyclic dependency with TF
#  imports:
#    - keras
#    - keras.backend
#    - keras.datasets
#    - keras.engine
#    - keras.layers
#    - keras.preprocessing
#    - keras.utils
#    - keras.wrappers

about:
  home: https://github.com/keras-team/keras
  license: MIT
  license_file: ../LICENSE
  summary: Deep Learning for Python

extra:
  recipe-maintainers:
    - open-ce/open-ce-dev-team
