{% set version = "2.14.0" %}

package:
  name: keras
  version: {{ version }}

source:
  - url: https://files.pythonhosted.org/packages/fe/58/34d4d8f1aa11120c2d36d7ad27d0526164b1a8ae45990a2fede31d0e59bf/keras-{{ version }}-py3-none-any.whl
    sha256: d7429d1d2131cc7eb1f2ea2ec330227c7d9d38dab3dfdf2e78defee4ecc43fcd

build:
  number: 1

requirements:
  host:
    - python {{ python }}
    - pip
  run:
    - python {{ python }}
    - keras-preprocessing >={{ keras_preprocessing }}
  run_constrained:
    - tensorflow {{ tensorflow }}

test:
  requires:
    - pip
  commands:
    - pip check
  # Cyclic dependency with tensorflow
  # imports:
  #  - keras

about:
  home: https://github.com/keras-team/keras
  license: MIT
  license_file: ../LICENSE
  summary: Deep Learning for Python

extra:
  recipe-maintainers:
    - open-ce/open-ce-dev-team
